### ISSUE TITLE
Some things I can not find answers to`

### ISSUE THREAD

**Issue by thesteve0** [NationalSecurityAgency/skills-docs#45]
Hey Awesome SkillTree people. 
I was looking through your documentation site, trying to see if you could be a replacement for our Katacoda site - https://learn.crunchydata.com

There were some pretty basic questions that I couldn't find answers for:

1. Where does an author actually write their content? It seems like it is in the description parameter of a skill. It would be great to show the markdown and then a screenshot of what you get.
2. When a student starts a skill do they get a terminal to work in?
3. How do you ensure a student has actually done the task before giving them points?

It seems like most of these questions (and more) would go in a content creator's guide to SkillTree

Thanks for reading
Steve

**Comment by mosefer** [comment]
@thesteve0 

Thank you so much for reaching out to us! Those are great questions and actually point out some omissions in our documentation that we need to rectify asap! SkillTree is a platform to _add_ self-directed, gamified learning to a tool as opposed to an entire training platform itself. For example, SkillTree could be integrated into the Katacode platform to provide levels/skills/achievements across different courses but could not itself be a direct replacement for Katacode.

The content for a SkillTree Training Profile is created within the Dashboard and you are correct that it is encapsulated in the Description parameter for a Skill. I'll create a ticket to provide better documentation on that aspect, we will also update the introduction in the documentation to provide a more clear explanation of what the platform is.

Since SkillTree is a platform to support _adding_ gamified learning to an application, we don't provide a terminal for a student to work in. Verification of actions/tasks performed would generally be through integration into the Tool or Application into which SkillTree is integrated, for example through reporting button clicks or interactions within the application to the SkillTree platform (the [integration guide](https://code.nsa.gov/skills-docs/skills-client/)  covers that reasonably well - although we welcome feedback on that!).
